[project]
name = "enable-chrome-ai"
version = "1.0"
description = "Enable Gemini in Chrome, AI Powered History search, DevTools Al Innovations in Google Chrome without cleaning data and reinstall."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psutil>=7.1.3",
]
